# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "simple"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.block_entities]

			[light_sources.settings.block_entities.minecraft]
				bed = true
				calibrated_sculk_sensor = true
				furnace = true
				dropper = true
				daylight_detector = true
				jukebox = true
				sign = true
				brewing_stand = true
				sculk_sensor = true
				hanging_sign = true
				brushable_block = true
				conduit = true
				beehive = true
				dispenser = true
				smoker = true
				lectern = true
				skull = true
				campfire = true
				barrel = true
				chest = true
				piston = true
				sculk_shrieker = true
				end_portal = true
				shulker_box = true
				enchanting_table = true
				banner = true
				structure_block = true
				sculk_catalyst = true
				ender_chest = true
				bell = true
				end_gateway = true
				comparator = true
				beacon = true
				command_block = true
				jigsaw = true
				hopper = true
				mob_spawner = true
				chiseled_bookshelf = true
				trapped_chest = true
				decorated_pot = true
				blast_furnace = true

			[light_sources.settings.block_entities.farmersdelight]
				basket = true
				canvas_sign = true
				stove = true
				cutting_board = true
				hanging_canvas_sign = true
				skillet = true
				cabinet = true
				cooking_pot = true

			[light_sources.settings.block_entities.handcrafted]
				container = true
				oven = true
				crockery = true

			[light_sources.settings.block_entities.regions_unexplored]
				hanging_sign_block_entity = true
				sign_block_entity = true

			[light_sources.settings.block_entities.biomesoplenty]
				anomaly = true
				sign = true
				hanging_sign = true

			[light_sources.settings.block_entities.amendments]
				wall_lantern = true
				carpeted_block = true
				skull_candle = true
				tool_hook = true
				water_lily_pad = true
				hanging_flower_pot = true
				skull_pile = true
				ceiling_banner = true
				liquid_cauldron = true

			[light_sources.settings.block_entities.another_furniture]
				service_bell = true
				drawer = true
				planter_box = true
				shelf = true

			[light_sources.settings.block_entities.easymagic]
				enchanting_table = true

			[light_sources.settings.block_entities.visualworkbench]
				crafting_table = true

			[light_sources.settings.block_entities.yigd]
				grave_block_entity = true

			[light_sources.settings.block_entities.betternether]
				furnace = true
				forge = true
				nether_brewing_stand = true
				chest_of_drawers = true

			[light_sources.settings.block_entities.brewery]
				brewingstation = true
				beer_mug = true
				silo = true

			[light_sources.settings.block_entities.doapi]
				standard = true
				flower_box = true
				sideboard = true
				flower_pot = true
				storage = true
				cabinet = true

			[light_sources.settings.block_entities.mynethersdelight]
				mnd_hsign = true
				mnd_sign = true
				nether_stove = true

			[light_sources.settings.block_entities.suppsquared]
				plaque = true

			[light_sources.settings.block_entities.expandeddelight]
				juicer = true

			[light_sources.settings.block_entities.comforts]
				sleeping_bag = true
				hammock = true

			[light_sources.settings.block_entities.yungscavebiomes]
				rare_ice = true

			[light_sources.settings.block_entities.backpacked]
				shelf = true

			[light_sources.settings.block_entities.vinery]
				basket = true
				mod_sign = true
				fermentation_barrel = true
				apple_press = true
				vinery_standard = true
				flower_pot = true
				storage = true
				cabinet = true
				mod_hanging_sign = true

			[light_sources.settings.block_entities.chimes]
				iron_wind_chime_block_entity = true
				crystal_wind_chime_block_entity = true
				copper_wind_chime_block_entity = true
				bamboo_wind_chime_block_entity = true
				glass_wind_bell_block_entity = true

			[light_sources.settings.block_entities.exposure]
				lightroom = true
				flash = true

			[light_sources.settings.block_entities.bclib]
				barrel = true
				chest = true
				furnace = true

			[light_sources.settings.block_entities.betterend]
				pedestal = true
				hydrother_malvent = true
				infusion_pedestal = true
				end_stone_smelter = true
				eternal_pedestal = true

			[light_sources.settings.block_entities.supplementaries]
				pedestal = true
				clock_block = true
				blackboard = true
				flag = true
				sack = true
				speaker_block = true
				key_lockable_tile = true
				bubble_block = true
				cannon = true
				bellows = true
				notice_board = true
				jar_boat = true
				cage = true
				lunch_basket = true
				rope_buntings = true
				bamboo_spikes = true
				trapped_present = true
				hourglass = true
				wind_vane = true
				moving_slidy_block = true
				doormat = true
				jar = true
				spring_launcher_arm = true
				item_shelf = true
				enderman_head = true
				turn_table = true
				faucet = true
				structure_temp = true
				block_generator = true
				book_pile = true
				rope_knot = true
				statue = true
				goblet = true
				urn = true
				flower_box = true
				pulley_block = true
				globe = true
				timber_frame = true
				suspicious_gravel_bricks = true
				safe = true
				present = true
				sign_post = true

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				zombie_horse = true
				axolotl = true
				egg = true
				zoglin = true
				spawner_minecart = true
				allay = true
				llama = true
				mule = true
				bat = true
				husk = true
				camel = true
				experience_bottle = true
				rabbit = true
				firework_rocket = true
				silverfish = true
				giant = true
				drowned = true
				item = true
				goat = true
				horse = true
				vindicator = true
				minecart = true
				spectral_arrow = true
				mooshroom = true
				llama_spit = true
				glow_item_frame = false
				snowball = true
				tnt = true
				parrot = true
				creeper = true
				lightning_bolt = true
				tadpole = true
				ravager = true
				evoker_fangs = true
				chest_minecart = true
				tropical_fish = true
				slime = true
				pillager = true
				area_effect_cloud = true
				blaze = true
				piglin = true
				end_crystal = true
				endermite = true
				ender_pearl = true
				zombie = true
				item_display = true
				guardian = true
				fireball = true
				illusioner = true
				eye_of_ender = true
				wither_skull = true
				wolf = true
				block_display = true
				zombie_villager = true
				tnt_minecart = true
				elder_guardian = true
				chest_boat = true
				boat = true
				small_fireball = true
				strider = true
				cave_spider = true
				cod = true
				witch = true
				snow_golem = true
				spider = true
				command_block_minecart = true
				panda = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				frog = true
				hoglin = true
				armor_stand = true
				experience_orb = true
				dolphin = true
				stray = true
				turtle = true
				shulker = true
				salmon = true
				wither_skeleton = true
				wandering_trader = true
				vex = true
				piglin_brute = true
				ocelot = true
				furnace_minecart = true
				item_frame = true
				phantom = true
				ender_dragon = true
				leash_knot = true
				evoker = true
				marker = true
				glow_squid = true
				warden = true
				squid = true
				shulker_bullet = true
				enderman = true
				dragon_fireball = true
				chicken = true
				sniffer = true
				trader_llama = true
				donkey = true
				fox = true
				iron_golem = true
				zombified_piglin = true
				cat = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				villager = true
				skeleton_horse = true
				fishing_bobber = true
				text_display = true
				polar_bear = true
				hopper_minecart = true
				falling_block = true
				painting = true
				interaction = true
				wither = true

			[light_sources.settings.entities.farmersdelight]
				rotten_tomato = true

			[light_sources.settings.entities.handcrafted]
				seat = true
				fancy_painting = true

			[light_sources.settings.entities.desolation]
				blackened = true
				ash_scuttler = true

			[light_sources.settings.entities.regions_unexplored]
				chest_boat = true
				boat = true

			[light_sources.settings.entities.vinery]
				mule = true
				dark_cherry_boat = true
				chair = true
				dark_cherry_chest_boat = true
				wandering_winemaker = true

			[light_sources.settings.entities.biomesoplenty]
				chest_boat = true
				boat = true

			[light_sources.settings.entities.amendments]
				falling_lantern = true

			[light_sources.settings.entities.creeperoverhaul]
				swamp_creeper = true
				bamboo_creeper = true
				jungle_creeper = true
				cave_creeper = true
				beach_creeper = true
				savannah_creeper = true
				spruce_creeper = true
				hills_creeper = true
				snowy_creeper = true
				badlands_creeper = true
				ocean_creeper = true
				dark_oak_creeper = true
				desert_creeper = true
				dripstone_creeper = true
				mushroom_creeper = true

			[light_sources.settings.entities.another_furniture]
				seat = true

			[light_sources.settings.entities.naturalist]
				deer = true
				snail = true
				alligator = true
				rhino = true
				bluejay = true
				snake = true
				catfish = true
				robin = true
				dragonfly = true
				boar = true
				caterpillar = true
				duck_egg = true
				tortoise = true
				duck = true
				butterfly = true
				bear = true
				sparrow = true
				lizard = true
				zebra = true
				rattlesnake = true
				canary = true
				firefly = true
				hippo = true
				coral_snake = true
				cardinal = true
				lion = true
				vulture = true
				bass = true
				giraffe = true
				lizard_tail = true
				elephant = true
				finch = true

			[light_sources.settings.entities.exposure]
				photograph = true
				photograph_frame = true

			[light_sources.settings.entities.promenade]
				sunken_skeleton = true
				capybara = true
				duck = true
				lush_creeper = true

			[light_sources.settings.entities.betternether]
				naga_projectile = true
				firefly = true
				flying_pig = true
				hydrogen_jellyfish = true
				skull = true
				jungle_skeleton = true
				naga = true

			[light_sources.settings.entities.bclib]
				chair = true

			[light_sources.settings.entities.brewery]
				beer_elemental = true
				hanging_rope = true
				rope_knot = true
				beer_elemental_attack = true
				rope_collision = true

			[light_sources.settings.entities.betterend]
				dragonfly = true
				cubozoa = true
				shadow_walker = true
				end_slime = true
				silk_moth = true
				end_fish = true

			[light_sources.settings.entities.supplementaries]
				dispenser_minecart = true
				slingshot_projectile = true
				brick_projectile = true
				pearl_marker = true
				falling_sack = true
				hat_stand = true
				bomb = true
				falling_ash = true
				falling_urn = true
				cannonball = true
				red_merchant = true
				rope_arrow = true
				slimeball_projectile = true

			[light_sources.settings.entities.dawn]
				custom_tnt = true
				flying_block = true

			[light_sources.settings.entities.doapi]
				chair = true

			[light_sources.settings.entities.mynethersdelight]
				strider_rock = true

			[light_sources.settings.entities.terraform]
				chest_boat = true
				boat = true

			[light_sources.settings.entities.yungscavebiomes]
				sand_snapper = true
				icicle = true
				ice_cube = true

			[light_sources.settings.entities.netherdepthsupgrade]
				magmacubefish = true
				searing_cod = true
				fortressgrouper = true
				bonefish = true
				lava_pufferfish = true

